### ISSUE TITLE
Upgrade from 0.7.x to 1.0.1

### ISSUE THREAD

**Issue by cyberz0mbie** [Revenact/Pterodactyl-Script#16]
panel-0.7.19/tests/Unit/Services/Users/UserUpdateServiceTest.php
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
Deprecation Notice: Class Sofa\Eloquence\Searchable\Searchable located in ./vendor/sofa/eloquence-base/src/Contracts/Searchable/Searchable.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Egulias\EmailValidator\Exception\ExpectedQPair located in ./vendor/egulias/email-validator/EmailValidator/Exception/ExpectingQPair.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Warning:  Uncaught ErrorException: require(/var/www/pterodactyl/vendor/composer/../../app/helpers.php): failed to open stream: No such file or directory in /var/www/pterodactyl/vendor/composer/autoload_real.php:69
Stack trace:
#0 /var/www/pterodactyl/vendor/composer/autoload_real.php(69): Composer\Util\ErrorHandler::handle(2, 'require(/var/ww...', '/var/www/pterod...', 69, Array)
#1 /var/www/pterodactyl/vendor/composer/autoload_real.php(69): require()
#2 /var/www/pterodactyl/vendor/composer/autoload_real.php(59): composerRequirea0d151e398db03fa80461f22de60bd0a('30714b87ced7441...', '/var/www/pterod...')
#3 /var/www/pterodactyl/vendor/autoload.php(7): ComposerAutoloaderInita0d151e398db03fa80461f22de60bd0a::getLoader()
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(43): require_once('/var/www/pterod...')
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(305): Illuminate\Foundation\ComposerScripts::postAutoloadDump(Object(Composer\Script\Even in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69

Warning: Uncaught ErrorException: require(/var/www/pterodactyl/vendor/composer/../../app/helpers.php): failed to open stream: No such file or directory in /var/www/pterodactyl/vendor/composer/autoload_real.php:69
Stack trace:
#0 /var/www/pterodactyl/vendor/composer/autoload_real.php(69): Composer\Util\ErrorHandler::handle(2, 'require(/var/ww...', '/var/www/pterod...', 69, Array)
#1 /var/www/pterodactyl/vendor/composer/autoload_real.php(69): require()
#2 /var/www/pterodactyl/vendor/composer/autoload_real.php(59): composerRequirea0d151e398db03fa80461f22de60bd0a('30714b87ced7441...', '/var/www/pterod...')
#3 /var/www/pterodactyl/vendor/autoload.php(7): ComposerAutoloaderInita0d151e398db03fa80461f22de60bd0a::getLoader()
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(43): require_once('/var/www/pterod...')
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(305): Illuminate\Foundation\ComposerScripts::postAutoloadDump(Object(Composer\Script\Even in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69
PHP Fatal error:  composerRequirea0d151e398db03fa80461f22de60bd0a(): Failed opening required '/var/www/pterodactyl/vendor/composer/../../app/helpers.php' (include_path='.:/usr/share/php') in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69

Fatal error: composerRequirea0d151e398db03fa80461f22de60bd0a(): Failed opening required '/var/www/pterodactyl/vendor/composer/../../app/helpers.php' (include_path='.:/usr/share/php') in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69
PHP Warning:  require(/var/www/pterodactyl/vendor/composer/../../app/helpers.php): failed to open stream: No such file or directory in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69
PHP Fatal error:  require(): Failed opening required '/var/www/pterodactyl/vendor/composer/../../app/helpers.php' (include_path='.:/usr/share/php') in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69
PHP Warning:  require(/var/www/pterodactyl/vendor/composer/../../app/helpers.php): failed to open stream: No such file or directory in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69
PHP Fatal error:  require(): Failed opening required '/var/www/pterodactyl/vendor/composer/../../app/helpers.php' (include_path='.:/usr/share/php') in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69
PHP Warning:  require(/var/www/pterodactyl/vendor/composer/../../app/helpers.php): failed to open stream: No such file or directory in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69
PHP Fatal error:  require(): Failed opening required '/var/www/pterodactyl/vendor/composer/../../app/helpers.php' (include_path='.:/usr/share/php') in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69
PHP Warning:  require(/var/www/pterodactyl/vendor/composer/../../app/helpers.php): failed to open stream: No such file or directory in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69
PHP Fatal error:  require(): Failed opening required '/var/www/pterodactyl/vendor/composer/../../app/helpers.php' (include_path='.:/usr/share/php') in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69
Your panel has successfully been updated to version 1.0.1
PHP Warning:  require(/var/www/pterodactyl/vendor/composer/../../app/helpers.php): failed to open stream: No such file or directory in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69
PHP Fatal error:  require(): Failed opening required '/var/www/pterodactyl/vendor/composer/../../app/helpers.php' (include_path='.:/usr/share/php') in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69
PHP Warning:  require(/var/www/pterodactyl/vendor/composer/../../app/helpers.php): failed to open stream: No such file or directory in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69
PHP Fatal error:  require(): Failed opening required '/var/www/pterodactyl/vendor/composer/../../app/helpers.php' (include_path='.:/usr/share/php') in /var/www/pterodactyl/vendor/composer/autoload_real.php on line 69

**Comment by cyberz0mbie** [comment]
Easier to read here > https://hastebin.com/bageyuloma.sql

**Comment by tommytran732** [comment]
@TheRealHeyJack Could you submit a PR for the fix?

**Comment by TheRealHeyJack** [comment]
Fixed in 31d01d90a3a8109dc0b39de76023d10051c7d6cd
