### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by hugolafougere** [Revenact/Pterodactyl-Script#19]
hello,

i believe there is an error in your pterodactyl install script 
info server:
debian 9
Dedicated server
install:
[6] Install the (0.7.19) panel and daemon.
[1] Nginx (recommended).
[1] No. "themes"
[2] No. "Block Ping "
[1] Yes. "Apply JavaPipe's kernel configurations"

error log: https://hastebin.com/erudegedin.less

installation error https://i.imgur.com/eN0FX9E.png

**Comment by lPlayFun** [comment]
Hello, this is a probleme with composer ! To fix this just open install.sh and add 

` composer self-update --1`
at line 886 after `    curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
` and before `    cp .env.example .env
`

**Comment by TheRealHeyJack** [comment]
Fixed in 31d01d90a3a8109dc0b39de76023d10051c7d6cd
