### ISSUE TITLE
Upgrade pannel 1.0.3 to 1.1.1

### ISSUE THREAD

**Issue by IdefixRC** [Revenact/Pterodactyl-Script#25]
Execute the script, select upgrade from 1.0 to 1.1.1
Script executes: Your panel has successfully been updated to version 1.1.1

Panel shows: Your panel is not up-to-date! The latest version is 1.1.1 and you are currently running version 1.0.3.
(tried restarting the server as well - same result).

No errors are thrown (aside from the usual question to not run composer as root).
I also had a quick look at the script and it looks like it downloads the correct file.
Any idea of why it does not work is appreciated.
Thanks

**Comment by tommytran732** [comment]
Done :+1:
