### ISSUE TITLE
0.7 Installation Script Does Not Work

### ISSUE THREAD

**Issue by josiaah** [Revenact/Pterodactyl-Script#27]
The 0.7 installation script isn't installing Pterodactyl properly. Always returns 500 Error.

**Comment by TheRealPikachu** [comment]
You know this is malware right? The creator of this repository was banned from MC Market for distribution of malware.

**Comment by TheRealHeyJack** [comment]
Hello @TheRealPikachu,

Please enlighten me on where the so-called "malware" is on an Open Source script that you can audit yourself and see.

Thanks

**Comment by TheRealPikachu** [comment]
The code is all copy and paste?

**Comment by TheRealHeyJack** [comment]
It's a install script what do you want it to do turn your lights on 😂

**Comment by TheRealPikachu** [comment]
Nobody should be using it.

**Comment by TheRealHeyJack** [comment]
Right, Think of this

Would you rather spend like 10-20mins setting it up
or
Would you rather spend like 5mins setting it up

**Comment by TheRealPikachu** [comment]
I would rather spend 10-20mins setting it up. As this is malware.

**Comment by TheRealHeyJack** [comment]
For someone who cannot view a simple shell script/have no idea how shell scripts work (literally executing Linux commands), I don't think you are in any position to tell people to not use it. Sure, if people have the time to install it manually (especially a lot of times), then by all means. But honestly, I think you probably cannot do that anyways, since you are the kind of ignorant people that scream a file in plain text (not even a binary!) on GitHub is malware. And for someone that talks about copy and pasted commands (which is mandatory btw, there aren't too many different ones to install packages)... please have a look at [YOUR OWN PROJECT](https://github.com/TheRealPikachu/DBM-Dashboard/blob/63fba3bc4632e782cb35c159298aea0ba047ebfd/website/index.html#L777) which literally reuses code from another FOSS project.  You are just here to trash the project on a legitimate issue opened by another user and I am kindly asking you to leave.

**Comment by TheRealPikachu** [comment]
Don't change the subject by mentioning my own projects. This repository was reported on MC Market before to contain malware. For someone who does not know about this, and thinks that MC Market isn't a thing, I am kindly asking you to leave. The owner of this repository is not even active.

**Comment by TheRealHeyJack** [comment]
1. I was quoting that you were being a hypocrite because you are.
2. X to Doubt
3. When did I say MCMarket wasn't a thing XD
4. Who are you to ask me to leave kek
5. I mean why do you think I maintain the project because he is busy smhmh

**Comment by tommytran732** [comment]
Actually, I am still pretty active. I am just a bit busy lately and i just think my time can be spent doing something more productive than arguing with a hopelessly ignorant individual as you. I mean, the code is literally there nad you can read everything yourself... It is near plain English.

Also Jake... maybe we shouldn't waste our time with tin foil hatters lol. They got nothing to contribute to society abyways.

**Comment by TheRealPikachu** [comment]
Don't be a dick, don't distribute malware, don't team with retards, don't
speak shit, don't encourage bad actions, and don't have bad grammar. Thank
you.

**Comment by tommytran732** [comment]
So I am a "dick" and "retard" for writing vode and giving it to people for free, while you on the other hand just came in to trash me without even reading it... Get a mirror and look at yourself will ya?

If you and your tin foil hat don't want to use it  then fine, it's your freedom. Don't come in here and act like you see malware inside the code or something. At this point, it looks like you either don't want to read it and are just here for trashing or you are incapable of reading/writing simple shell scripts and are trying to be a wannabe security researcher. 

Please, Github is not a place for you to look for attention. It is for developing and contributing to free and open source software. Don't turn it into a circus.

**Comment by TheRealPikachu** [comment]
I'm not acting, I've never done this before, just with your repository
because you are distributing malware.

**Comment by tommytran732** [comment]
Which part of it is malware or is the tin foil hat covering up your eyes?

**Comment by TheRealPikachu** [comment]
The code.

**Comment by TheRealPikachu** [comment]
Look, your main has obviously been banned and you are refusing to admit
this. Might as well get this taken off GitHub.

**Comment by tommytran732** [comment]
I have never been banned from github, what are you even talking about?

**Comment by TheRealPikachu** [comment]
Revenact

**Comment by tommytran732** [comment]
What? Revenact is my website. I changed the repo from my personal account to the org.

**Comment by TheRealPikachu** [comment]
Revenact/Pterodactyl-Script

**Comment by tommytran732** [comment]
It's not banned? The repo is literally on Github right now. You are mentally insane.

**Comment by TheRealPikachu** [comment]
The user, not the repo. We've already reported you to GitHub, so end of
conversation. My inbox is running out of storage.

**Comment by Ifera** [comment]
Why the hell is this shitshow still going on @tommytran732. Just ban this idiot already.. and maybe close this issue and make a new one with the same description. Like seriously.. Enough of this dick measuring contest.

**Comment by TheRealPikachu** [comment]
Who the fuck are you calling an idiot. I've had enough of this shit. This
is none of your business, so kindly fuck off.

**Comment by Ifera** [comment]
> Who the fuck are you calling an idiot. 
Uhh.. you! :)

**Comment by TheRealPikachu** [comment]
Sarcasm 100
Do I care 0

**Comment by tommytran732** [comment]
Lol Revenact is the org, not the user... I dont think this guy even knows how to use Github.

**Comment by josiaah** [comment]
I'm going to close this issue, i have been quietly reading this issue chat and i'm frankly laughing at this Pikachu kid.

**Comment by tommytran732** [comment]
Just an update: this is fixed in https://github.com/Revenact/Pterodactyl-Script/commit/3debf707c61acd2c7db75f25d432581940f6a47d
