### ISSUE TITLE
error on install panel v0.7.19

### ISSUE THREAD

**Issue by elima151** [Revenact/Pterodactyl-Script#29]
Composer (version 2.0.8) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
Class Sofa\Eloquence\Searchable\Searchable located in ./vendor/sofa/eloquence-base/src/Contracts/Se
rchable/Searchable.php does not comply with psr-4 autoloading standard. Skipping.
Class Egulias\EmailValidator\Exception\ExpectedQPair located in ./vendor/egulias/email-validator/Em
ilValidator/Exception/ExpectingQPair.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In PackageManifest.php line 122:

  Undefined index: name

Script @php artisan package:discover handling the post-autoload-dump event returned with error code
1

In PackageManifest.php line 122:

  Undefined index: name

In PackageManifest.php line 122:

  Undefined index: name

In PackageManifest.php line 122:

  Undefined index: name

To use PHP's internal mail sending, select [mail]. To use a custom SMTP server, select [smtp]. TLS
ncryption is recommended.

In PackageManifest.php line 122:

  Undefined index: name

In PackageManifest.php line 122:

  Undefined index: name

In PackageManifest.php line 122:

  Undefined index: name

Creating panel queue listeners...
Installing Let's Encrypt and creating an SSL certificate...

**Comment by HaloFloof** [comment]
Hello,

This is an issue that should be fixed in the script, but it's basically that the latest version of Composer breaks Pterodactyl 0.7, so you just have to run these commands:

```sudo rm /usr/local/bin/composer
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=1.10.16```

@tommytran732 I think this should be an easy fix to implement in the install script. :)

**Comment by tommytran732** [comment]
> Hello,
> 
> This is an issue that should be fixed in the script, but it's basically that the latest version of Composer breaks Pterodactyl 0.7, so you just have to run these commands:
> 
> `sudo rm /usr/local/bin/composer`
> `curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=1.10.16`
> 
> @tommytran732 I think this should be an easy fix to implement in the install script. :)

Thank you! I will add the fix later today.

**Comment by tommytran732** [comment]
Fixed in https://github.com/Revenact/Pterodactyl-Script/commit/3debf707c61acd2c7db75f25d432581940f6a47d
