### ISSUE TITLE
No files are being downloaded

### ISSUE THREAD

**Issue by MeowedAt** [Revenact/Pterodactyl-Script#32]
**Note: for support questions, please use the [Discord](https://revenact.io/discord)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x ] Bug Report

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **[Pastebin](https://pastebin.com) link of the error**

No error

* **What is the expected behavior?**

To download the script

* **What is the motivation / use case for changing the behavior?**

It isn't downloading the script when I run `curl -Ls https://api.github.com/repos/Revenact/Pterodactyl-Script/releases/latest | grep -wo "https.*install.sh" | wget -qi -`

* **Please tell us about your environment:**

```
  - Version: v0.0.6
  - OS: [Ubuntu 20.04 (Tried on 18.04)]
```

Running `dir` does nothing. I am using root

**Comment by icedmoca** [comment]
> **Note: for support questions, please use the [Discord](https://revenact.io/discord)**. This repository's issues are reserved for feature requests and bug reports.
> 
> * **I'm submitting a ...**
>   
>   * [x ] Bug Report
> * **Do you want to request a _feature_ or report a _bug_?**
> 
> Bug
> 
> * **[Pastebin](https://pastebin.com) link of the error**
> 
> No error
> 
> * **What is the expected behavior?**
> 
> To download the script
> 
> * **What is the motivation / use case for changing the behavior?**
> 
> It isn't downloading the script when I run `curl -Ls https://api.github.com/repos/Revenact/Pterodactyl-Script/releases/latest | grep -wo "https.*install.sh" | wget -qi -`
> 
> * **Please tell us about your environment:**
> 
> ```
>   - Version: v0.0.6
>   - OS: [Ubuntu 20.04 (Tried on 18.04)]
> ```
> 
> Running `dir` does nothing. I am using root

You aren't wrong. It can't find a https trail with install.sh at the end.
Maybe removed?

**Comment by icedmoca** [comment]
You aren't wrong. It can't find a https trail with install.sh at the end.
Maybe removed?

**Comment by tommytran732** [comment]
Fixed.
