### ISSUE TITLE
update plz 

### ISSUE THREAD

**Issue by ipwnosx** [Revenact/Pterodactyl-Script#42]
plz update to 1.5.0

**Comment by dension0** [comment]
Pls update to PHP 8 Panel to v1.5.0 and wings to v1.4.6

**Comment by ipwnosx** [comment]
> Pls update to PHP 8 Panel to v1.5.0 and wings to v1.4.6

you can use this, https://pterodactyl.io/panel/1.0/updating.html ,  I recommend manual updating.

**Comment by tommytran732** [comment]
Done.
